services:
  anathema_server:
    container_name: anathema_server
    image: anathema:latest
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    depends_on:
      - anathema_redis

  anathema_redis:
    container_name: anathema_redis
    restart: unless-stopped
    image: redis:8.0
    ports:
      - 6379:6379
    command: [ "redis-server", "--save", "" ]
